name: ci

on:
  push:
  pull_request:

jobs:
  rust-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup rust
        uses: dtolnay/rust-toolchain@stable

      - name: cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: cargo test
        run: cargo test --all-features
